### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by meetmangukiya** [flocktex/flocktex.github.io#3]
- [ ] Name: Flock Tex LLP
- [ ] About
- [ ] Logo
     - [ ] Font in Logo
     - [ ] Colours used in logo
- [ ] Address
- [ ] Letterhead
